---
title: "county plots"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggrepel)
library(hrbrthemes)
```

```{r, purl=FALSE}
source("./functions.R")
```


```{r}
theme_set(theme_ft_rc(plot_title_size = 24,
                      subtitle_size = 18,
                      axis_text_size = 16,
                      caption_size = 12) +
          theme(text = element_text(size = 20),
                axis.title.x = element_text(size = 14),
                axis.title.y = element_text(size = 14)))
```


```{r}
county_data <- read_csv("./nytimes-data/us-counties.csv")

selected_county_data <- county_data %>%
  filter((county == "Cook"& state == "Illinois") |
         (county == "Milwaukee" & state == "Wisconsin") |
         (county == "Waukesha" & state == "Wisconsin") |
         (county == "Dane" & state == "Wisconsin") |
         (county == "King" & state == "Washington") |
         (county == "Los Angeles" & state == "California") |
         (county == "San Francisco" & state == "California") |
         (county == "Wayne" & state == "Michigan") |
         (county == "New York City" & state == "New York") |
         (county == "Orleans" & state == "Louisiana") |
         (county == "Miami-Dade" & state == "Florida") |
         (county == "Dallas" & state == "Texas")) %>%
  mutate(county = fct_reorder(county, cases, max))
```

```{r}
county_colors <- gg_color_hue(length(levels(selected_county_data$county)))
names(county_colors) <- levels(selected_county_data$county)
```


```{r}
death_data <- selected_county_data %>%
  group_by(state, county) %>%
  mutate(diff = deaths - lead(deaths)) %>%
  filter(deaths > 0, deaths != 1 | diff != 0) %>%
  mutate(n = seq(0, n() - 1)) %>%
  ungroup()

synthetic <- generate_synthetic_data(1, c(1, 2, 3, 4), 2.3 * max(death_data$deaths)) %>%
  rename(deaths = value) %>%
  filter(n <= max(death_data$n))

synthetic_text <- synthetic %>%
  group_by(days_to_double) %>%
  summarize(x = last(n),
            y = last(deaths)) %>%
  mutate(text = c("Deaths double\nevery day",
                  "..every\n2 days",
                  "..every\n3 days",
                  "..every\n4 days"))

death_points <- death_data %>%
  group_by(county) %>%
  filter(n == max(n)) %>%
  ungroup()

p_00_county <- death_data %>%
  ggplot(aes(x = n, y = deaths)) +
  geom_line(data = synthetic, aes(group = days_to_double), alpha = 0.9, linetype = "dashed") + # synthetic
  geom_text(data = synthetic_text, aes(x = x, y = y, label = text), inherit.aes = FALSE, nudge_x = -0.5, size = 5) +
  geom_line(aes(color = county)) +
  geom_point(data = death_points, aes(color = county)) +
  geom_text_repel(data = death_points, aes(label = county, color = county), size = 7, hjust = 1, vjust = 1) +
  scale_y_log10(labels = scales::label_number_si()) +
  theme(legend.position = "None") +
  scale_color_manual(values = county_colors) +
  labs(x = "day",
       title = "County cumulative deaths",
       caption = "Source: https://github.com/nytimes/covid-19-data")
```

```{r, purl=FALSE}
p_00_county
```


```{r}
cases_init <- 10

cases_data <- selected_county_data %>%
  filter(cases >= cases_init) %>%
  group_by(county, state) %>%
  mutate(n = seq(0, n() - 1)) %>%
  ungroup()

synthetic <- generate_synthetic_data(cases_init, c(1, 2, 3, 4), 2 * max(cases_data$cases)) %>%
  rename(cases = value) %>%
  filter(n <= max(cases_data$n))

synthetic_text <- synthetic %>%
  group_by(days_to_double) %>%
  summarize(x = last(n),
            y = last(cases)) %>%
  mutate(text = c("Casess double\nevery day",
                  "..every\n2 days",
                  "..every\n3 days",
                  "..every\n4 days"))

cases_points <- cases_data %>%
  group_by(county) %>%
  filter(n == max(n)) %>%
  ungroup()  
    
p_01_county <- cases_data %>%
  ggplot(aes(x = n, y = cases)) +
  geom_line(data = synthetic, aes(group = days_to_double), alpha = 0.9, linetype = "dashed") + # synthetic
  geom_text(data = synthetic_text, aes(x = x, y = y, label = text), inherit.aes = FALSE, nudge_x = -0.5, size = 5) +
  geom_line(aes(color = county)) +
  geom_point(data = cases_points, aes(color = county)) +
  geom_text_repel(data = cases_points, aes(label = county, color = county), size = 7, hjust = 1, vjust = 1) +
  scale_y_log10(labels = scales::label_number_si()) +
  theme(legend.position = "None") +
  scale_color_manual(values = county_colors) +
  labs(x = "day",
       title = "County cumulative cases",
       caption = "Source: https://github.com/nytimes/covid-19-data")
```

```{r, purl=FALSE}
p_01_county
```


```{r, purl=FALSE}
cumulative_cases <- county_data %>%
  group_by(state, county) %>%
  filter(cases == max(cases)) %>%
  ungroup() %>%
  arrange(desc(cases))

top_50_counties <- cumulative_cases %>%
  filter(county != "Unknown") %>%
  head(50)

state_key <- seq(1, 50)
names(state_key) <- state.name

top_50_county_data <- county_data %>%
  semi_join(top_50_counties, by = c("state", "county")) %>%
  mutate(name = paste(county, state.abb[state_key[state]], sep = ", "))

top_50_cases_data <- top_50_county_data %>%
  mutate(name = fct_reorder(name, cases, max, .desc = TRUE),
         group = as.integer(name)) %>%
  filter(cases > 9) %>%
  arrange(state, county, date) %>%
  group_by(name) %>%
  mutate(n = seq(0, n() - 1)) %>%
  ungroup()

top_50_cases_points <- top_50_cases_data %>%
  group_by(name) %>%
  filter(cases == max(cases)) %>%
  ungroup()

top_50_cases_text <- top_50_cases_data %>%
  distinct(name) %>%
  mutate(n = 1, cases = max(top_50_cases_data$cases - 1e4))
  
top_50_cases_data %>%
  ggplot(aes(x = n, y = cases)) +
  facet_wrap(~ name, ncol = 5) + 
  geom_line(data = (top_50_cases_data %>% select(-name)), aes(group = group), alpha = 0.6) +
  geom_line(color = ft_cols$red) + 
  geom_point(data = top_50_cases_points, color = ft_cols$red) +
  geom_text(data = top_50_cases_text, 
            aes(label = name), 
            color = ft_cols$red,
            vjust = "inward",
            hjust = "inward") +
  theme_ft_rc() +
  theme(strip.text = element_blank(),
        panel.spacing.x = unit(-0.05, "lines"),
        panel.spacing.y = unit(0.3, "lines")) + 
  scale_y_log10(labels = scales::label_number_si())
```

